### PR TITLE
readme.md to README.md and `author.username` fallback

### PR DESCRIPTION
**Pull request by tunnckoCore**
- README.md is standard and you used it for long time, why you start using readme.md?
- maybe should use `parse-git-config` and `git-config-path` directly, if we want user email

### CODE REVIEW

**Comment by jonschlinkert** [comment]
> README.md is standard and you used it for long time, why you start using readme.md?

I don't know, I didn't think about it. it just changed at some point lol. we can change it back.

> maybe should use parse-git-config and git-config-path directly, if we want user email

sounds good. this was just a starting point to get it working, thanks

**Comment by tunnckoCore** [comment]
> sounds good.

Yea, but no so... only because one email to read and parse gitconfig? Because currently would read and parse gitconfig only if anything fails to find `username`

**Comment by jonschlinkert** [comment]
> Yea, but no so... only because one email to read and parse gitconfig

wait what? I'm starting to get confused by what you're saying. I merged this, do you want it published, or should I revert?

**Comment by tunnckoCore** [comment]
It's okey. I'm talking for the `email` addition.

**Comment by jonschlinkert** [comment]
k, got it

**Pull request merged**
